GAME_NAME = 'Breakout'

WIDTH = 600
HEIGHT = 600

BALL_SIZE = '20'
BALL_COLOR = 'violet'

PUDDLE_WIDTH = 10
PUDDLE_HEIGHT = 100
PUDDLE_COLOR = 'black'

SCORE_SIZE = 20
SCORE_COLOR = 'lightblue'

END_TEXT_SIZE = 30
END_TEXT_COLOR = 'red'